language: java
sudo: false

jdk: openjdk11

git:
  submodules: false

install: true
script: "./travis.sh"
env:
  - TEST=CI
matrix:
  fast_finish: true

before_cache:
  # remove all the artifacts that are installed in local repo because of mvn deploy
  - rm -rf $HOME/.m2/repository/org/sonarsource/roslynsdk
  - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar'
    - '$HOME/jvm'
    - '$HOME/maven'

notifications:
  email: false
  webhooks:
    urls:
      - secure: Pp4yrQP4jM+D98givxkO4fQhepZng77aeP81EmtbsrgWhwGU9csr4XohSAixs+KugsErEfHn5I65NB3M3cTM0usDWnoV8xBaVBWxLd6w7OJQ384CQWM4DjpAMCuU7auT1F/2EwXOcDFrgeOiI5Rc+zrzIwpUi2fJ0TGfLzDy9bWrKHSYG6wOynjbOn603xvzijqW3dRH/ti+hUgM07IPPaDpQ4tO71+5GGhPY2Bm6PK9ysnaZdK6GrFw2OWzlg5uEIWVFpbwL92lEMKTTUPExrgQcjQiBhF7VFp+0XerhfkIQ59nlJ6PDKYSPhY5SKOEzOZ/xd2MQO1dW+KXltAdEoGNPYj+/a/OCtEwW8X5IDcEwaCWizchYRfwgdD6uzgqRM4C6T+e/lXMKxUTZqkPFeZg4zeYMo5/DdovJNNb0Zv9+8Iek6Czkp4XQIiG4eAR9bMzIa+pnL5ud+THmZgwjFWA7EyPRbl9XgTxwRvxis3+BC+QcHhvd0fl01WJw+wkih1Tr8gvaPCB+A6cnL7uRcN5tRG7c6zv+TcRln4Qdi7WrYM2BmWEvs0b9GdRStp7Ad9zSNZ76kkInNbnsVVpVogYdTsdCzHtaryRNw2D8DqfHwECoqb0ymG1VQTZ1XH1gJ8w58ztZpaJYS5buczIXsTv/0xp5bDH2AjJe+PF54E=
    on_start: always
